### ISSUE TITLE
negative margin-top on desktop browsers

### ISSUE THREAD

**Issue by TwentyOneSolutions** [jschr/bootstrap-modal#266]
I added this patch and it does a nice job.  it definitely fixes many issues with mobile browsers.

I see a problem with desktop browsers, though.  if I do not include the javascript, then on Chrome it works fine, while on IE the modal box is opened towards the bottom of the page.

when I add the javascript though, both on Chrome and on IE the modal box has a negative margin-top which takes the top of the box out of the viewport.

I get for the modal class an inline-style of  `margin-top: -151px;`

where is it coming from and how can I fix it?

this is using bootstrap-modal.js v2.2.5

TIA

**Comment by jschr** [comment]
What version of BS are you using? The latest (2.2.6) contains fixes for BS3.3 so that could be your issue.

**Comment by TwentyOneSolutions** [comment]
BS v2.3.2

but please note that as mentioned above I'm using bootstrap-modal v2.2.5

**Comment by TwentyOneSolutions** [comment]
sorry, I was using v2.2.6 without the latest patch https://github.com/jschr/bootstrap-modal/compare/2.2.6...master which threw me off when I reported the version.

I downgraded to v2.2.5 and am still experiencing the same issue.

I also sent you an email in case it went to junk box.

thank you.

**Comment by TwentyOneSolutions** [comment]
the problem occurs at
https://github.com/jschr/bootstrap-modal/blob/master/js/bootstrap-modal.js#L146

    this.$element
        .css('margin-top', 0 - this.$element.height() / 2)    // offensive line
        .removeClass('modal-overflow');

I'm not sure why it affects me but not all of the other users though (since no one has reported it thus far).

**Comment by jschr** [comment]
@TwentyOneSolutions do you have an accessible page or a jsfiddle where I can see the issue?

**Comment by TwentyOneSolutions** [comment]
it's accessible temporarily at http://www.100candles.com/?bootstrap-modal 

click the link that reads "Free Ground Shipping" or "Low Price Guarantee"

![image](https://cloud.githubusercontent.com/assets/885907/6870662/9e1f4f56-d45a-11e4-8c27-cd5ab03a00c2.png)

**Comment by jschr** [comment]
I believe the issue is being caused by conflicting styles:

![Screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_15198/TZRAGJtXvuECCAlXNHcjjCoRzUSLfe/100Candles.com%2B-%2BCandles%252C%2BCandle%2BHolders%252C%2BBattery%2BCandles%252C%2Band%2BLED%2BLights%2B2015-03-27%2B11-57-41.png?Expires=1427558302&Signature=CCvC4eKW1ZbU1-Bw~EUmc5FcGKYlVL~ZXAaJoxrtwyuonLy646jxjOMPgjuqU3125sRDdU5LluS-vhK3VYmY2CmK4IHusT0NVGtAi3MYY2jSSLa4SK0SL-By7pIK4Ahokfzxbh0K-zIrR4ovn2luVxfw1RycX4TmhdblMa85M15HiVMrusc~~oFjM6li6aL73F02pTjTtWNaP17VNgFitvF~7lsYg3TjKX4SYYQYS5PALq9tTIE9~Rx3FyQ4c0417izms~8T13SIR7GbT5cRDRTgfwZsCeqo77OIlkLzq3UVjvN702y0IXzA8JFw6SakcXWq-lhbHizmxzAM1yvF6w__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Make sure the bootstrap-modal.css file is inserted after boostrap.css

**Comment by TwentyOneSolutions** [comment]
Thank you!  I had customized the modal in the past and had some leftovers of that that caused the issue.

I really appreciate your time and expertise.
