### ISSUE TITLE
Issue with Bootbox

### ISSUE THREAD

**Issue by quillford** [jschr/bootstrap-modal#268]
[This](https://github.com/makeusabrew/bootbox/issues/416) should shed some light on my issue.

**Comment by jschr** [comment]
The issue seems to be caused by the fact that this plugin was originally designed for bootstrap 2.x so the latest bootbox (which relies on BS 3.x) wouldn't be compatible with this plugin.

Is there a need to use this plugin at all if you're using bootbox? You could also use bootbox v3, which was built using BS 2.x but I don't really like recommending downgrading. My recommendation is not to use my plugin if possible in your case since BS3/bootbox together should solve most of the issues that BS2 modals had.

**Comment by ThaDafinser** [comment]
See also https://github.com/makeusabrew/bootbox/issues/200

Can multiple modals be used without `bootstrap-modal`?
I think then its possible to use BS3/bootbox only

**Comment by ThaDafinser** [comment]
@jschr i tried now several variations, but come back to your plugin

http://nakupanda.github.io/bootstrap3-dialog/
- has cool things, but does not work with the "original" modals / has a custom styling

http://bootboxjs.com/
- has also cool things, but does not work with your component

Overall the other 2 are just "smart" boilerplates for some common overlay "types", but your plugin enhances the original modal functions.

- multiple modals (with correct backdrop) <-- biggest thing for me
- dynamic height to screen size

**Comment by FreeAsInBeer** [comment]
Unfortunately I wasn't able to use this plugin with bootbox. This plugin provides more features so I decided to stick with this and drop bootbox.

**Comment by jschr** [comment]
Sorry everyone, I do want to be compatible with these other projects but I just don't have the time to make a BS3 compatible version at the moment. 

If anyone out there wants to have a go at it I'd gladly work with you and give you credit as a maintainer.
